### PR TITLE
RxSwift Update - Observable.create

### PR DESCRIPTION
**Pull request by kbala**
Fixed the Compile Error.

### CODE REVIEW

**Comment by nanoxd** [comment]
Thanks!

**Comment by kbala** [comment]
Hi @nanoxd Carthage Update fails. any fix?

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Check\ Pods\ Manifest.lock /Users/kbala/Library/Developer/Xcode/DerivedData/RxRealm-eduugjbpisactrdqwlghpegkzgla/Build/Intermediates/RxRealm.build/Release-iphoneos/RxRealm.build/Script-D2787D04A42A97D5C1BC4428.sh
(1 failure)
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Check\ Pods\ Manifest.lock /Users/kbala/Library/Developer/Xcode/DerivedData/RxRealm-eduugjbpisactrdqwlghpegkzgla/Build/Intermediates/RxRealm.build/Release-iphoneos/RxRealm.build/Script-D2787D04A42A97D5C1BC4428.sh
(1 failure)

**Comment by nanoxd** [comment]
I'll take a look at this later this afternoon and get back to you :smile:

**Comment by kbala** [comment]
Thanks,
Also, rx_objects not observing when add new row?

**Pull request merged**
